import type { Metadata } from "next";
import { Sidebar } from "@/components/sidebar.component";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <main className="flex items-center h-screen overflow-hidden">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
