import type { Metadata } from "next";
import { Sidebar } from "@/components/sidebar.component";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Bitscale",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="flex min-h-dvh flex-col">
        <main className="flex min-h-dvh flex-col overflow-hidden md:h-dvh md:flex-row">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
